---
title: "little bit of bitting from Mr. Konstantin"
author: "Оксана Владимировна Айзсилниекс"
date: "08 04 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Необходимые пакеты

```{r, message=FALSE, warning=FALSE}
library(DESeq2)
library(ggplot2)
library(clusterProfiler)
library(org.Hs.eg.db)
library(pheatmap)
library(dplyr)
library(plotly)
library(grid)
library(futile.logger)
library(VennDiagram)
library(amap)
options(width=120)
```


```{r, message=FALSE, warning=FALSE}
counts_trouble <- read.csv("GSE89633_counts.tsv", sep = "\t", row.names = 1)  
conditions_trouble <- read.csv("GSE89633_conditions.tsv", sep = "\t", row.names = 1)  
View(counts_trouble)
dim(counts_trouble)
dim(conditions_trouble)
head(conditions_trouble)
head(counts_trouble)
```

```{r, message=FALSE, warning=FALSE}
dds_trouble <- DESeqDataSetFromMatrix(countData = counts_trouble,
                              colData = conditions_trouble,
                              design = ~ conditions + cells)

vst_dds_trouble <- vst(dds_trouble)
counts.norm <- assay(vst_dds_trouble)

```

Строим PCA и видим, что явных аутлайеров нет. Большая часть вариации в наших данных объясняется, судя по всему, типом клетки (cell_type)


```{r PCA, message=FALSE, warning=FALSE}

pca_data <- prcomp(t(counts.norm))
percents <- pca_data$sdev^2 / sum(pca_data$sdev^2)
to_plot <- t(counts.norm) %*% pca_data$rotation


ggplotly(plotPCA(vst_dds_trouble, intgroup=c("conditions", "cells"), ntop = 500) + theme_bw())

```

```{r order and deseq object, message=FALSE, warning=FALSE}
dds_decr <- order(rowSums(counts(dds_trouble)), decreasing = TRUE)
dds_trouble <- dds_trouble[dds_decr, ][1:8000,]
dds_trouble <- DESeq(dds_trouble)
dds_trouble_log <- assay(rlog(dds_trouble))

clustering_it_wow <- Kmeans(dds_trouble_log, 8, method="correlation", iter.max=20000)

head(clustering_it_wow$cluster)
```

```{r heatmap, message=FALSE, warning=FALSE}
want_to_see_now <- dds_trouble_log[order(clustering_it_wow$cluster), order(conditions_trouble$cells, conditions_trouble$conditions)]

cluster <- as.factor(clustering_it_wow$cluster)
cluster_today <- as.data.frame(cluster)

want_to_see_now <- t(apply(want_to_see_now, 1, function(r) {
  (r - min(r)) / (max(r) - min(r))
}))

pheatmap(want_to_see_now, 
         show_rownames = F, cluster_rows = F,
         cluster_cols=F,
         annotation_col = conditions_trouble,
         annotation_row =  cluster_today)
```

# Попробуем проделать анализ дифференциальной экспрессии генов

```{r deseq objects, message=FALSE, warning=FALSE}
# FB
FB_cond <- conditions_trouble[conditions_trouble$cells == "cell type: FB", ]

FB_counts <- counts_trouble[,rownames(FB_cond)]

dds_trouble_FB <- DESeqDataSetFromMatrix(countData = FB_counts,
                              colData = FB_cond,
                              design = ~ conditions)

dds_trouble_FB <- dds_trouble_FB[rowSums(counts(dds_trouble_FB)) > 20, ]
dds_FB <- DESeq(dds_trouble_FB)

# FAP

FAP_cond <- conditions_trouble[conditions_trouble$cells == "cell type: FAP", ]

FAP_counts <- counts_trouble[,rownames(FAP_cond)]

dds_trouble_FAP <- DESeqDataSetFromMatrix(countData = FAP_counts,
                              colData = FAP_cond,
                              design = ~ conditions)

dds_trouble_FAP <- dds_trouble_FAP[rowSums(counts(dds_trouble_FAP)) > 20, ]
dds_FAP <- DESeq(dds_trouble_FAP)

# SMP

SMP_cond <- conditions_trouble[conditions_trouble$cells == "cell type: SMP", ]

SMP_counts <- counts_trouble[,rownames(SMP_cond)]

dds_trouble_SMP <- DESeqDataSetFromMatrix(countData = SMP_counts,
                              colData = SMP_cond,
                              design = ~ conditions)

dds_trouble_SMP <- dds_trouble_SMP[rowSums(counts(dds_trouble_SMP)) > 20, ]
dds_SMP <- DESeq(dds_trouble_SMP)

```

```{r diff_exp, message=FALSE, warning=FALSE}

res_FB <- results(dds_FB)
res_FB <- res_FB[order(res_FB[,4]),]

res_FAP <- results(dds_FAP)
res_FAP <- res_FAP[order(res_FAP[, 4]), ]

res_SMP <- results(dds_SMP)
res_SMP <- res_SMP[order(res_SMP[, 4]), ]
```

Если предполагать по volcano, то, похоже, меняется транскрипционная активность клеток FAP после двойного нокаута

```{r volcano, message=FALSE, warning=FALSE}
genes_FB <- rownames(res_FB)
genes_FAP <- rownames(res_FAP)
genes_SMP <- rownames(res_SMP)

gdata_FB <- data.frame(
  log_fold_change=res_FB$log2FoldChange,
  p_adj=res_FB$padj,
  n = "FB WT vs FB DKO"
)

gdata_FAP <- data.frame(
  log_fold_change=res_FAP$log2FoldChange,
  p_adj=res_FAP$padj,
  n = "FAP WT vs FAP DKO"
)

gdata_SMP <- data.frame(
  log_fold_change=res_SMP$log2FoldChange,
  p_adj=res_SMP$padj,
  n = "SMP WT vs SMP DKO"
)


general_gdata <- rbind(gdata_FB, gdata_FAP, gdata_SMP)
general_gdata <- na.omit(general_gdata)

# создадим порог значимости

general_gdata$threshold <- general_gdata$p_adj <= 0.01
general_gdata$significant <- sapply(general_gdata$threshold, function(x) ifelse(x == TRUE, "Significant", "Not Significant"))
general_gdata <- na.omit(general_gdata)

# строим 

ggplot(general_gdata,aes(x=log_fold_change, y=-log10(p_adj), col = significant)) +
       facet_grid(. ~ n) +
       geom_point(size=1) +
       theme_bw() +
       scale_colour_manual(values = c("black", "red")) + 
       labs(x = "Log fold change", y ="Adjusted p.value")+
       geom_hline(yintercept=2, linetype = 2, size = 1, colour = 'red')

```

```{r vienn, message=FALSE, warning=FALSE}
for_set_1 <- rownames(res_FB[which(res_FB$padj < 0.01),])
for_set_2 <- rownames(res_FAP[which(res_FAP$padj < 0.01),])
for_set_3 <- rownames(res_SMP[which(res_SMP$padj < 0.01),])

n12 <- length(intersect(for_set_1, for_set_2))
n23 <- length(intersect(for_set_2, for_set_3))
n13 <- length(intersect(for_set_1, for_set_3))
n123 <- length(intersect(intersect(for_set_1, for_set_2), for_set_3))

#wanted_sected <- intersect(intersect(for_set_1, for_set_2), for_set_3)

#length(wanted_sected) # 84

venn_plot <- draw.triple.venn(length(for_set_1), length(for_set_2), length(for_set_3), n12, n23, n13, n123, category = c("FB", "FAP", "SMP"), fill = c("blue", "pink", "black"), ext.line.lty = "dashed")

```

